### ISSUE TITLE
Keep search field visible

### ISSUE THREAD

**Issue by fregante** [hankxdev/one-click-extensions-manager#147]
I'm trying it out with a lot of random extensions installed. Performance is good (M1 Pro though)

I think all it needs is something like:

```css
header {
  position: sticky;
  top: 0;
  background: inherit;
  padding: some padding probably
}
```

![scroll](https://github.com/user-attachments/assets/36983829-3cd3-4f14-9ef5-53e539dfba30)
